# Generated by Django 4.2 on 2024-06-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="currency",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
