# Generated by Django 4.2 on 2024-06-04 13:48

from django.db import migrations, models, transaction
from countryinfo import CountryInfo


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_alter_country_currency_alter_country_flag_and_more"),
    ]

    @transaction.atomic
    def init_country(apps, schema_editor):
        coutries = []
        country_model = apps.get_model("master", "Country")
        for k, country in CountryInfo().all().items():
            try:
                name = country.get("name")
                alpha_2 = country.get("ISO", {}).get("alpha2", "")
                currency = country.get("currencies", [])[0]
                flag_url = f"/static/flags/{alpha_2.lower()}.gif"
                coutries.append(
                    country_model(name=name, flag=flag_url, currency=currency)
                )
            except Exception as e:
                print(f"Skip {k} = {e}")
                continue
        try:
            country_model.objects.bulk_create(coutries)
        except Exception as e:
            print("Failed init countries data :", e)

    operations = [
        migrations.RunPython(init_country, migrations.RunPython.noop),
    ]
