# Generated by Django 4.2 on 2024-06-04 13:48

from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_init_country"),
    ]

    @transaction.atomic
    def init_category(apps, schema_editor):
        country_model = apps.get_model("master", "Country")
        category_model = apps.get_model("master", "Category")
        categories = [
            {
                "country": "china",
                "title": "Electronic",
                "price_per_kilo": 250000,
            },
            {
                "country": "china",
                "title": "Chip",
                "price_per_kilo": 300000,
            },
            {
                "country": "china",
                "title": "Laptop and Computer",
                "price_per_kilo": 220000,
            },
            {
                "country": "thailand",
                "title": "Garments",
                "price_per_kilo": 200000,
            },
            {
                "country": "singapore",
                "title": "Spare parts",
                "price_per_kilo": 210000,
            },
        ]
        for c in categories:
            country = country_model.objects.filter(
                name__iexact=c.get("country")
            ).first()
            if country is None:
                print(f"Skip country {c.get('country')} not found!")
                continue
            c.update({"country": country})
            category_model.objects.create(**c)

    operations = [
        migrations.RunPython(init_category, migrations.RunPython.noop),
    ]
