# Generated by Django 4.2 on 2024-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_init_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(
                help_text="static url for this flag", max_length=255, unique=True
            ),
        ),
    ]
